on: [push, pull_request]

name: Rust

jobs:
  lint:
    name: Build & lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rust-src, rustfmt, clippy
        
    - name: Install xbuild
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-xbuild
        version: latest

    - name: Install system dependencies
      run: sudo apt update

    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Clippy
      run: make clippy

    - name: Build
      run: make all
